alg = input('Digite algo:')
print('O tipo primitivo desse valor é:', type(alg))
print('Tem somente espaços?' , alg.isspace())
print('É um número?', alg.isnumeric())
print('É alfabético?', alg.isalpha())
print('É alfanumérico?', alg.isalnum())
print('Está com maiúsculas?', alg.isupper())
print('Está com minúsculas?', alg.islower())
print('Está captalizada?', alg.istitle())